export const praxisData = [
  {
    previewpic: "/praxistage/deckblatt/tag1.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag1",
  },
  {
    previewpic: "/praxistage/deckblatt/tag2.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag2",
  },
  {
    previewpic: "/praxistage/deckblatt/tag3.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag3",
  },
  {
    previewpic: "/praxistage/deckblatt/tag4.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag4",
  },
  {
    previewpic: "/praxistage/deckblatt/tag5.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag5",
  },
  {
    previewpic: "/praxistage/deckblatt/tag6.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag6",
  },
  {
    previewpic: "/praxistage/deckblatt/tag7.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag7",
  },
  {
    previewpic: "/praxistage/deckblatt/tag8.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag8",
  },
  {
    previewpic: "/praxistage/deckblatt/tag9.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag9",
  },
  {
    previewpic: "/praxistage/deckblatt/tag10.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag10",
  },
  {
    previewpic: "/praxistage/deckblatt/tag11.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag11",
  },
  {
    previewpic: "/praxistage/deckblatt/tag12.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag12",
  },
  {
    previewpic: "/praxistage/deckblatt/tag13.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag13",
  },
  {
    previewpic: "/praxistage/deckblatt/tag14.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag14",
  },
  {
    previewpic: "/praxistage/deckblatt/tag15.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag15",
  },
  {
    previewpic: "/praxistage/deckblatt/tag16.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag16",
  },
  {
    previewpic: "/praxistage/deckblatt/tag17.png",
    date: "01.01.2023",
    description: "Beschreibung vom Praxistag",
    thema: "Das | Thema",
    tag: "tag17",
  },
];
